version: '3.8'
services:
  resume-analyzer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./checkpoints.db:/app/checkpoints.db
    restart: unless-stopped
